spring:
  application:
    name: mindbridge-backend
  profiles:
    active: local

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: never
  info:
    env:
      enabled: false
