import { motion } from 'framer-motion';
import { CheckCircle, Shield, Database } from 'lucide-react';

export default function AIKnowledgeBase() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h1 className="text-2xl font-semibold text-textMain">AI & Knowledge Base</h1>
        <p className="text-textMuted">Manage AI settings and knowledge sources.</p>
      </motion.div>

      {/* Knowledge sources */}
      <div className="grid md:grid-cols-2 gap-4">
        {[
          { name: 'WHO Mental Health Guidelines', status: 'active', docs: 245 },
          { name: 'CBT Techniques Library', status: 'active', docs: 128 },
          { name: 'DBT Skills Collection', status: 'active', docs: 89 },
          { name: 'Vietnamese Mental Health Resources', status: 'review', docs: 67 },
        ].map((source, i) => (
          <motion.div
            key={i}
            className="bg-surface rounded-2xl p-5 shadow-soft border border-gray-100"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 + i * 0.05 }}
          >
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Database className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium text-textMain">{source.name}</h3>
                  <p className="text-sm text-textMuted">{source.docs} documents</p>
                </div>
              </div>
              <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                source.status === 'active' 
                  ? 'bg-primary/10 text-primary' 
                  : 'bg-accent/20 text-accent'
              }`}>
                {source.status === 'active' ? 'Active' : 'In Review'}
              </span>
            </div>
            <div className="flex gap-2">
              <button className="px-3 py-1.5 bg-surfaceMuted text-textMain text-sm rounded-lg hover:bg-gray-200 transition-colors">
                Edit
              </button>
              <button className="px-3 py-1.5 bg-primary/10 text-primary text-sm rounded-lg hover:bg-primary/20 transition-colors">
                Sync
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Safety validation status */}
      <motion.div
        className="bg-surface rounded-2xl p-6 shadow-soft"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        <h2 className="font-semibold text-textMain mb-4">Safety Validation</h2>
        <div className="space-y-4">
          {[
            { label: 'RAG System Status', status: 'operational' },
            { label: 'Content Moderation', status: 'operational' },
            { label: 'Risk Detection Engine', status: 'operational' },
            { label: 'Human-in-the-Loop', status: 'active' },
          ].map((item, i) => (
            <div key={i} className="flex items-center justify-between">
              <span className="text-textMuted">{item.label}</span>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-primary" />
                <span className="text-sm text-primary capitalize">{item.status}</span>
              </div>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Explainable AI notes */}
      <motion.div
        className="bg-gradient-to-br from-primary/5 to-secondary/5 rounded-2xl p-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
      >
        <div className="flex items-center gap-3 mb-4">
          <Shield className="w-5 h-5 text-primary" />
          <h2 className="font-semibold text-textMain">Explainable AI Notes</h2>
        </div>
        <p className="text-sm text-textMuted leading-relaxed">
          All recommendations generated by MindBridge AI include explanations based on user data.
          Each suggestion references specific check-ins, mood patterns, or resource content to help
          users understand why a particular recommendation was made.
        </p>
      </motion.div>
    </div>
  );
}
